# pylint: disable=relative-beyond-top-level, too-few-public-methods
"""
Attribut mapper for mongo db connector
"""

from typing import Any, Self
import re

import sqlite3

from stricto import SFilter, Operator

from ...db_handler import DBHandler
from .attribute_mapper import Sqlite3AttributeMapper, Sqlite3RefAttributeMapper, Sqlite3_idAttributeMapper, Sqlite3DictAttributeMapper, Sqlite3ListAttributeMapper, Sqlite3RefsListAttributeMapper
from .item_mapper import Sqlite3ItemMapper
from ....error import NotFoundError, DBError
from .request import (
    Sqlite3DeleteRequest,
    Sqlite3UpdateRequest,
    Sqlite3CreateRequest,
    Sqlite3SearchRequest,
    Sqlite3SelectRequest,
)

from ...request import Response

class DBSqlite3Connector(DBHandler):
    """
    DBConnector for sqlite3

    """

    def __init__(
        self,
        db_file: str,
        table_name: str,
        item_mapper: Sqlite3ItemMapper = Sqlite3ItemMapper(
            default_attribute_mapper=Sqlite3AttributeMapper()
        ),
        **kwargs,
    ):
        """


        :param db_file: the filename where the DB is stored
        :type db_file: str
        :param item_mapper: a specific ItemMapper, defaults to Sqlite3ItemMapper( default_attribute_mapper=Sqlite3AttributeMapper() )
        :type item_mapper: Sqlite3ItemMapper, optional
        """

        self._db_file = db_file
        self._table_name = table_name

        self._db = sqlite3.connect(self._db_file, **kwargs)

        super().__init__(f"{db_file}({table_name})", item_mapper, **kwargs)

        self.item_mapper.add_type_mappers("Ref", Sqlite3RefAttributeMapper())
        self.item_mapper.add_type_mappers("RefsList", Sqlite3RefsListAttributeMapper())
        self.item_mapper.add_type_mappers("List", Sqlite3ListAttributeMapper())
        self.item_mapper.add_type_mappers("Dict", Sqlite3DictAttributeMapper())
        self.item_mapper.add_attribute_mappers("$._id", Sqlite3_idAttributeMapper())

        self.connect()

    def connect(self):
        """Try to make a connection to the mongodb

        :raise BDError: Raise an error in case of database Error

        """
        try:
            self._cursor = self._db.cursor()
        except Exception as e:
            raise DBError('Sqlite3 connection error at "{0}"', self._db_file) from e

    def close(self):
        """Close the mongodb connection

        :raise DBError: Raise an error in case of database Error

        """
        try:
            return self._db.close()
        except Exception as e:
            raise DBError('Sqlite3 close error at "{0}"', self._db_file) from e

    def drop(self) -> None:
        """
        Drop the entire collection

        """
        try:
            pass
        except Exception as e:
            raise DBError(
                'Sqlite3 connection error while "{0}.drop()"', self._db_file
            ) from e

    def generate_id(self, o: dict) -> str:  # pylint: disable=unused-argument
        """
        Not used in Sqlite3
        (the _id is generated by the DB itself)
        """
        raise DBError("Cannot use generate_id() in  DBSqlite3Connector")

    def db_build_search_request(self, request: Sqlite3SearchRequest) -> Any:
        """
        Build the Search request

        :param request: the request
        :type request: SearchRequest
        :return: a mongo query for this request
        :rtype: Any
        """
        return f'id == "{request._id}"', request._id

    def db_search(self, search_request: tuple) -> Any:
        """get one"""
        where_condition, _id = search_request

        try:
            pass
        except Exception as e:
            raise DBError(
                'Sqlite3 connection error while "{0}.find_one()"', self._db_file
            ) from e

        # if o is None:
        #     raise NotFoundError('_id "{0}" not found in "{1}"', _id, self._name)
        # o["_id"] = _id
        # return o
        return None

    def db_build_delete_request(self, request: Sqlite3DeleteRequest) -> Any:
        """
        Build the Delete request

        :param request: the request
        :type request: DeleteRequest
        :return: a mongo query for this request
        :rtype: Any
        """
        return f'id == "{request._id}"', request._id

    def db_delete(self, delete_request: tuple) -> Any:
        """delete"""
        where_condition, _id = delete_request

        try:
            pass
        except Exception as e:
            raise DBError(
                'Sqlite3 connection error while "{0}.delete_one()"', self._db_file
            ) from e

        # if result.deleted_count == 1:
        #     return True
        #
        # raise NotFoundError('_id "{0}" not found in "{1}"', _id, self._name)
        return False

    def db_build_update_request(self, request: Sqlite3UpdateRequest) -> Any:
        """
        Build the Update Request

        :param request: the request
        :type request: UpdateRequest
        :return: a mongo query for this request
        :rtype: Any
        """
        return f'id == "{request._id}"', request._id, request._data

    def db_update(self, _id: str, update_request: tuple) -> Any:
        """update one"""
        where_condition, o, _id = update_request

        try:
            pass
        except Exception as e:
            raise DBError(
                'Sqlite3 connection error while "{0}.find_one_and_replace()"',
                self._db_file,
            ) from e

        return True



    def create(self, o: Any) -> str:  # pylint: disable=unused-argument
        """Create the object into the DB and return the _id

        :param o: The object given (json format)
        :type o: dict
        :raise Error: Raise an error DBError or any db error

        """

        if self.item_mapper:
            self.item_mapper.do_pre_write(o)

        req = Sqlite3CreateRequest(o, self.item_mapper)
        data = self.db_create(self.db_build_create_request(req))
        resp = Response()
        resp.data = data
        return resp.data

    def db_build_create_request(self, request: Sqlite3CreateRequest) -> Any:
        """
        Build the Update Create Request

        :param request: the request
        :type request: CreateRequest
        :return: the data
        :rtype: Any
        """

        request.split( self._name )        
        return request.requests

    def db_create(self, requests: list[ str ]) -> Any:
        """create"""
        try:
            for request in requests:
                self._cursor.execute(request)
            self._db.commit()
        except Exception as e:
            raise DBError(
                'Sqlite3 connection error while "{0}.create()"', self._db_file
            ) from e

        return str(self._cursor.lastrowid)

    def db_build_select_request(self, request: Sqlite3SelectRequest) -> Any:
        """
        transform SFilter ( request._filter ) to mongodb filter

        :return: _description_
        :rtype: Any
        """
        return (
            self.item_mapper._sfilter_to_sql_query(request._filter),
            request._projection,
            request._page_size,
            request._num_of_element_to_skip,
            request._sort_object,
        )

    def db_select(self, select_request: Any) -> Any:
        """select"""
        where_condition, projection, page_size, num_of_element_to_skip, sort_object = (
            select_request
        )

        print(f"select {projection} where { where_condition } {sort_object}")

        try:
            pass
        except Exception as e:
            raise DBError(
                'Sqlite3 connection error while "{0}.find()"', self._db_file
            ) from e
        return None

    def select(
        self,
        select_filter: SFilter,
        projection: list[str] = [],
        page_size: int = 0,
        num_of_element_to_skip: int = 0,
        sort_object: dict = None,
    ) -> Response:  # pylint: disable=unused-argument
        """
        Select from filter in the DB and return a list of dicts, with pagination

        :param select_filter: The filter for selection (depends on DB types)
        :param projection: The list of elements we want for each object
        :type projection: dict
        :param page_size: number of elements per page
        :type page_size: int
        :param num_of_element_to_skip: number of element to skip from beginning
        :type num_of_element_to_skip: int
        :param sort_object: Soon
        :type sort_object: dict
        :raise Error: Raise an error DBError or any db error

        """
        req = Sqlite3SelectRequest(
            select_filter, projection, page_size, num_of_element_to_skip, sort_object
        )
        data = self.db_select(self.db_build_select_request(req))
        resp = Response()
        if self.item_mapper:
            if isinstance(data, list):
                for d in data:
                    self.item_mapper.do_post_read(d)

        resp.data = data
        return resp.data
