# pylint: disable=relative-beyond-top-level, too-few-public-methods
"""
Attribut mapper for mongo db connector
"""

from typing import Any
import copy

import sqlite3

from stricto import SFilter

from ..generic.db_handler import DBHandler
from ...error import NotFoundError, DBError

from .transformers import IdTransformer, BooleanTransformer
from ..generic.transformer import Transformer
from ..generic.interface import SelectResponse
from .pragma import TablePragma, SqlFieldDescription
from .filter import SQlite3Filter


class DBSqlite3Connector(DBHandler):
    """
    DBConnector for sqlite3

    """

    def __init__(
        self,
        db_file: str,
        table_name: str,
        **kwargs,
    ):
        """


        :param db_file: the filename where the DB is stored
        :type db_file: str
        :param item_mapper: a specific ItemMapper, defaults to Sqlite3ItemMapper( default_attribute_mapper=Sqlite3AttributeMapper() )
        :type item_mapper: Sqlite3ItemMapper, optional
        """

        self._db_file = db_file
        self._table_name = table_name

        self.pragmas: dict[str, TablePragma] = {}

        # Transformers
        self.transformers: dict[str, dict[str, Transformer]] = {}
        self.type_transformers: dict[str, Transformer] = {}

        self._db = sqlite3.connect(self._db_file, **kwargs)

        super().__init__(f"{db_file}({table_name})", **kwargs)

        self._db_file = db_file
        self._table_name = table_name

        self.register_transformer(IdTransformer())
        self.register_type_transformer(BooleanTransformer())

        self.filter = SQlite3Filter(self._table_name, self.get_transformer)

        self.connect()

    def connect(self):
        """Try to make a connection to the mongodb

        :raise BDError: Raise an error in case of database Error

        """
        try:
            self._cursor = self._db.cursor()
        except Exception as e:
            raise DBError('Sqlite3 connection error at "{0}"', self._db_file) from e

    def close(self):
        """Close the mongodb connection

        :raise DBError: Raise an error in case of database Error

        """
        try:
            return self._db.close()
        except Exception as e:
            raise DBError('Sqlite3 close error at "{0}"', self._db_file) from e

    def _drop_table(self, table_name: str, key_path: list[str], model: dict) -> None:
        """
        Drop a table (a main table or a sub table)
        and follow all its fields to check for sub tables.

        :param table_name: the table name
        :type table_name: str
        :param key_path: the table is attach to a key in case of a sub table
        :type key_path: list[str]
        :param model: the model related to the key path
        :type model: dict
        """

        if "sub_scheme" in model:
            for k, v in model["sub_scheme"].items():
                new_key_path = key_path.copy()
                new_key_path.append(k)
                self._drop_table(table_name, key_path + [k], v)
            return

        db_key = "_".join(key_path)

        # A list
        if "sub_type" in model:
            sub_model = model["sub_type"]
            sub_table_name = f"{table_name}_{db_key}"
            self._drop_table(sub_table_name, [], sub_model)
            return

        self._cursor.execute(f"DELETE FROM {table_name}").fetchall()

        return

    def drop(self) -> None:
        """
        Drop the entire collection

        """
        self._drop_table(self._table_name, [], self.model)
        self._db.commit()

    def generate_id(self, o: dict) -> str:  # pylint: disable=unused-argument
        """
        Not used in Sqlite3
        (the _id is generated by the DB itself)
        """
        raise DBError("Cannot use generate_id() in  DBSqlite3Connector")

    def _set_table_info(self, table_name: str) -> TablePragma:
        """
        Fill the TablePragma for this table

        :param table_name: the name of the table
        :type table_name: str
        :return: the TablePragma found or created
        :rtype: TablePragma
        """

        if table_name in self.pragmas:
            tp = self.pragmas[table_name]
        else:
            tp = TablePragma(table_name)
            self.pragmas[table_name] = tp

            res = self._cursor.execute(
                f'SELECT name FROM sqlite_master WHERE name=="{table_name}"'
            ).fetchone()
            if res is not None:
                tables = list(res)
                if len(tables) == 1:

                    current_pragmas = self._cursor.execute(
                        f"PRAGMA table_info({table_name});"
                    ).fetchall()

                    for current_pragma in current_pragmas:
                        cp = SqlFieldDescription(current_pragma)
                        tp.add_db_field(cp)

                    current_foreigns = self._cursor.execute(
                        f"PRAGMA foreign_key_list({table_name});"
                    ).fetchall()

                    for current_foreign in current_foreigns:
                        cp = SqlFieldDescription(None, current_foreign)
                        tp.add_db_field(cp)

            f = SqlFieldDescription()
            f.create("id", {"types": ["Int"], "required": False})
            f._pk = True
            tp.add_backo_field(f)

        return tp

    def _reccursive_check_structure(
        self, table_name: str, key_path: list[str], model: dict
    ) -> None:
        """
        Check the structure of the table if compliant to the model

        :param table_name: the table name
        :type table_name: str
        :param key_path: the key path
        :type key_path: list[str]
        :param model: the model of the key path
        :type model: dict
        """

        tp = self._set_table_info(table_name)

        # A Dict
        if "sub_scheme" in model:

            for k, v in model["sub_scheme"].items():
                new_key_path = key_path.copy()
                new_key_path.append(k)
                self._reccursive_check_structure(table_name, new_key_path, v)
            return

        # A List
        if "sub_type" in model:
            sub_table_name = f"{table_name}_{'_'.join(key_path)}"
            self._reccursive_check_structure(sub_table_name, [], model["sub_type"])

            tp_sub = self._set_table_info(sub_table_name)
            f1 = SqlFieldDescription()
            f1.create(f"{table_name}_id", {"types": ["Int"], "required": False})
            f1._ref_table = table_name
            f1._ref_field = "id"
            tp_sub.add_backo_field(f1)

            return

        # In case of a list of not a Dict,
        if not key_path:
            key_path = ["_"]

        transformer = self.get_transformer(key_path, table_name)
        store_in_db = True
        db_path = key_path
        if transformer:
            store_in_db = transformer.must_be_store_in_db()
            db_path = transformer.get_db_path()
        if store_in_db:
            f = SqlFieldDescription()
            f.create("_".join(db_path), model)
            tp.add_backo_field(f)

    def check_structure(self, update_directly=False) -> tuple[bool, str]:
        """
        Check all tables and sub tables

        :return: True if sqlie3 tables are compliants to backo
        :rtype: bool
        """
        self.pragmas.clear()
        message = ""

        self._reccursive_check_structure(self._table_name, [], self.model)

        some_changements = False

        for t_name, tp in self.pragmas.items():
            s = tp.get_pragma()
            if s:
                some_changements = True

                if update_directly:
                    self._cursor.executescript(s)
                else:
                    message += f'/* --- table "{t_name}" ---- */\r\n'
                    message += s
                    message += "\r\n\r\n"
            else:
                if not update_directly:
                    message += f"/* Nothing to change on table {tp._name} */\r\n\r\n"

        if some_changements and update_directly:
            self._db.commit()

        return (not some_changements, message)

    def _search_in_table(
        self, table_name: str, id_name: str, sqlite3_id: int
    ) -> list[dict]:
        """
        Do a SELECT into the table for a specific _id name == sqlite3_id

        :param table_name: the table name
        :type table_name: str
        :param id_name: the name of the field
        :type id_name: str
        :param sqlite3_id: the id in the equal
        :type sqlite3_id: int
        :raises NotFoundError: if not found
        :return: datas found as a list of dict
        :rtype: list[dict]
        """
        list_of_results = self._cursor.execute(
            f"SELECT * FROM {table_name} WHERE {id_name} == ?", (sqlite3_id,)
        ).fetchall()

        # None or empty
        if not list_of_results:
            return []

        l = []
        for res in list_of_results:
            obj = {}
            for idx, attribute in enumerate(self._cursor.description):
                key_path = attribute[0]
                value = res[idx]
                obj[key_path] = value
            l.append(obj)
        return l

    def load(
        self, table_name: str, key_path: list[str], model: dict, loaded_object: dict
    ) -> Any:
        """
        Do the load of an object and transform it with transformers


        :param table_name: the name of the table
        :type table_name: str
        :param key_path: the key path
        :type key_path: list[str]
        :param model: its model in backo
        :type model: dict
        :param loaded_object: the loaded object for the key path
        :type loaded_object: dict
        :return: the loaded value for the key path
        :rtype: Any
        """
        transformer = self.get_transformer(key_path, table_name, model["types"])
        if transformer:
            transformer.on_load(loaded_object, key_path)

        db_key = "_".join(key_path)

        # A dict
        if "sub_scheme" in model:
            o = {}
            for k, v in model["sub_scheme"].items():
                o[k] = self.load(table_name, key_path + [k], v, loaded_object)
            return o

        # A list
        if "sub_type" in model:
            sub_model = model["sub_type"]
            sub_table_name = f"{table_name}_{db_key}"
            sub_objects = self._search_in_table(
                sub_table_name, f"{table_name}_id", loaded_object["id"]
            )
            values = []
            for sub_object in sub_objects:
                sub = self.load(table_name, [], sub_model, sub_object)
                values.append(sub)
            return values

        # A normal value
        if db_key not in loaded_object:
            return None

        return loaded_object[db_key]

    def search(self, _id: str) -> dict:  # pylint: disable=unused-argument
        """
        Do a search

        """
        list_of_items = self._search_in_table(self._table_name, "id", int(_id))
        if not list_of_items:
            raise NotFoundError('_id "{0}" not found in "{1}"', _id, self._name)

        o = self.load(self._table_name, [], self.model, list_of_items[0])
        return o

    def get_by_id(self, _id: str) -> dict:
        """do a get"""
        return self.search(_id)

    def _delete_in_table(
        self, table_name: str, id_name: str, sqlite3_id: int
    ) -> list[int]:
        """
        Delete in a DB with a WHERE id_name == sqlite3_id

        :param table_name: the table name
        :type table_name: str
        :param id_name: the name of the field
        :type id_name: str
        :param sqlite3_id: the value
        :type sqlite3_id: int
        :raises NotFoundError: if not found
        :return: _descThe list of deleted _ids
        :rtype: list[ int ]
        """
        print(f"DELETE FROM {table_name} WHERE {id_name} == {sqlite3_id} RETURNING id")
        list_of_results = self._cursor.execute(
            f"DELETE FROM {table_name} WHERE {id_name} == ? RETURNING id", (sqlite3_id,)
        ).fetchall()

        # None or empty results
        if not list_of_results:
            return []
            # raise NotFoundError(
            #     "{0} == {1} not found in table {2}", id_name, sqlite3_id, table_name
            # )
        deleted_ids = [res[0] for res in list_of_results]
        return deleted_ids

    def _reccursive_delete(
        self, table_name: str, key_path: list[str], deleted_ids: list[int], model: dict
    ) -> None:
        """
        Delete in a table and all its sub table if needed

        :param table_name: the table name
        :type table_name: str
        :param key_path: the current key path
        :type key_path: list[str]
        :param deleted_ids: the list od deleted ids to delete in the table
        :type deleted_ids: list[int]
        :param model: the current model for the key path
        :type model: dict
        """

        if "sub_scheme" in model:
            for k, v in model["sub_scheme"].items():
                new_key_path = key_path.copy()
                new_key_path.append(k)
                self._reccursive_delete(table_name, key_path + [k], deleted_ids, v)
            return

        db_key = "_".join(key_path)

        # A list
        if "sub_type" in model:
            sub_model = model["sub_type"]
            sub_table_name = f"{table_name}_{db_key}"
            for deleted_id in deleted_ids:
                sub_deleted_ids = self._delete_in_table(
                    sub_table_name, f"{table_name}_id", deleted_id
                )
                self._reccursive_delete(sub_table_name, [], sub_deleted_ids, sub_model)
            return

        return

    def delete_by_id(self, _id):
        """delete"""
        ids = self._delete_in_table(self._table_name, "id", int(_id))
        if not ids:
            raise NotFoundError('_id "{0}" not found in "{1}"', _id, self._name)

        self._reccursive_delete(self._table_name, [], ids, self.model)
        self._db.commit()

    def _create_in_table(
        self, table_name: str, keys_values: list[tuple[str, Any]]
    ) -> int:
        """
        Do the creation in the table

        :param table_name: the name of the table
        :type table_name: str
        :param keys_values: list of key, values
        :type keys_values: list[tuple[str, Any]]
        :return: the id created
        :rtype: int
        """
        r = tuple(map(tuple, zip(*keys_values)))
        t = ("?",) * len(r[0])
        print(f"INSERT INTO {table_name} {r[0]} VALUES ({', '.join(t) })", r[1])
        self._cursor.execute(
            f"INSERT INTO {table_name} {r[0]} VALUES ({', '.join(t) })", r[1]
        )
        created_id = self._cursor.lastrowid
        return created_id

    def _reccursive_create(
        self,
        table_name: str,
        key_path: str,
        o: dict,
        model: dict,
        keys_values: list[tuple[str, Any]],
    ) -> int | None:
        """
        Do the creation and creation in sub tables if needed

        :param table_name: the table name
        :type table_name: str
        :param key_path: the key_path
        :type key_path: str
        :param o: the object to insert
        :type o: dict
        :param model: the schem for this key_path
        :type model: dict
        :param keys_values: list of key - values
        :type keys_values: list[ tuple[ str, Any ]]
        :return: the created id
        :rtype: int
        """

        transformer = self.get_transformer(key_path, table_name, model["types"])
        db_path = key_path
        if transformer:
            if transformer.must_be_store_in_db() is False:
                return None
            db_path = transformer.get_db_path()

        # A Dict
        if "sub_scheme" in model and isinstance(o, dict):

            sqlite3_id = None
            # Put the List objects at the end to do the creation forst to get th id for the next
            for k, v in sorted(
                model["sub_scheme"].items(), key=lambda item: "sub_type" in item[1]
            ):
                new_key_path = key_path.copy()
                new_key_path.append(k)
                if k in o:
                    my_id = self._reccursive_create(
                        table_name, new_key_path, o[k], v, keys_values
                    )
                    if sqlite3_id is None:
                        sqlite3_id = my_id
            return sqlite3_id

        # A List
        if "sub_type" in model and isinstance(o, list):
            sqlite3_id = self._create_in_table(table_name, keys_values)
            keys_values.clear()

            sub_table_name = f"{table_name}_{'_'.join(key_path)}"
            for d in o:
                kv = [(f"{table_name}_id", sqlite3_id)]
                self._reccursive_create(sub_table_name, [], d, model["sub_type"], kv)
                self._create_in_table(sub_table_name, kv)
                kv.clear()

            return sqlite3_id

        # In case of a list of not a Dict,
        if not db_path:
            db_path = ["_"]

        keys_values.append((f"{'_'.join(db_path)}", o))
        return None

    def create(self, o: Any) -> str:  # pylint: disable=unused-argument
        """Create the object into the DB and return the _id

        :param o: The object given (json format)
        :type o: dict
        :raise Error: Raise an error DBError or any db error

        """
        keys_values = []
        _id = self._reccursive_create(self._table_name, [], o, self.model, keys_values)
        if keys_values:
            _id = self._create_in_table(self._table_name, keys_values)
        self._db.commit()
        return str(_id)

    def _insert_in_table(self, table_name: str, _id: int, keys_values: dict) -> None:
        """
        Do an insert into a table

        :param table_name: the table_name
        :type table_name: str
        :param _id: the _id
        :type _id: int
        :param keys_values: list of key - values
        :type keys_values: dict
        """

        l = []
        v = []
        for key, value in keys_values.items():
            l.append(f"{key} = ?")
            v.append(value)

        v.append(_id)
        print(f'UPDATE {table_name} SET {", ".join(l)} WHERE id == ?, {tuple(v)}')
        self._cursor.execute(
            f'UPDATE {table_name} SET {", ".join(l)} WHERE id == ?', tuple(v)
        )

    def _reccursive_save(
        self,
        table_name: str,
        _id: int,
        key_path: list[str],
        o: dict,
        model: dict,
        keys_values: dict,
    ) -> None:
        """
        Do an update and do update into sub tables or update
        key_values with keys and values (in case of a Dict)

        UPDATE nom_table
            SET colonne1 = valeur1,
                colonne2 = valeur2
        WHERE condition;

        :param table_name: the table name
        :type table_name: str
        :param key_path: the key path
        :type key_path: list[ str ]
        :param o: the data to insert as a dict
        :type o: dict
        :param model: the model for key_path
        :type model: dict
        :param keys_values: the list of key values (can be modified)
        :type keys_values: _type_
        """

        transformer = self.get_transformer(key_path, table_name, model["types"])
        db_path = key_path
        if transformer:
            if transformer.must_be_store_in_db() is False:
                return
            db_path = transformer.get_db_path()

        # A Dict
        if "sub_scheme" in model and isinstance(o, dict):

            # Put the List objects at the end to do the creation forst to get th id for the next
            for k, v in sorted(
                model["sub_scheme"].items(), key=lambda item: "sub_type" in item[1]
            ):
                new_key_path = key_path.copy()
                new_key_path.append(k)
                if k in o:
                    self._reccursive_save(
                        table_name, _id, new_key_path, o[k], v, keys_values
                    )
            return

        # A List
        # delete all elements from the list and recreate it.
        if "sub_type" in model and isinstance(o, list):
            self._insert_in_table(table_name, _id, keys_values)
            keys_values.clear()

            sub_table_name = f"{table_name}_{'_'.join(key_path)}"
            sub_deleted_ids = self._delete_in_table(
                sub_table_name, f"{table_name}_id", _id
            )
            self._reccursive_delete(
                sub_table_name, [], sub_deleted_ids, model["sub_type"]
            )

            for d in o:
                kv = [(f"{table_name}_id", _id)]
                self._reccursive_create(sub_table_name, [], d, model["sub_type"], kv)
                self._create_in_table(sub_table_name, kv)
                kv.clear()

            return

        # In case of a list of not a Dict,
        if not db_path:
            db_path = ["_"]

        keys_values["_".join(db_path)] = o

    def save(self, _id: str, o: dict) -> None:
        """save"""
        keys_values = {}
        self._reccursive_save(
            self._table_name, int(_id), [], o, self.model, keys_values
        )
        if keys_values:
            self._insert_in_table(self._table_name, int(_id), keys_values)
        self._db.commit()

    def _reccursive_select(
        self, table_name: str, fields_to_get: str, select_filter: SFilter, model: dict
    ):
        pass

    def select(  # pylint: disable=unused-argument
        self,
        select_filter: SFilter,
        projection: list[str] = None,
        page_size: int = 0,
        num_of_element_to_skip: int = 0,
        sort_object: list[str] = None,
    ) -> SelectResponse:
        """
        Select from filter in the DB and return a list of dicts, with pagination

        :param select_filter: The filter for selection (depends on DB types)
        :param projection: The list of elements we want for each object
        :type projection: dict
        :param page_size: number of elements per page
        :type page_size: int
        :param num_of_element_to_skip: number of element to skip from beginning
        :type num_of_element_to_skip: int
        :param sort_object: Soon
        :type sort_object: dict
        :raise Error: Raise an error DBError or any db error

        """
        response = SelectResponse(page_size, num_of_element_to_skip)

        where_conditions, values = self.filter.build_db_filter(select_filter)
        select = f"SELECT * FROM {self._table_name} WHERE {where_conditions}"

        if page_size:
            values += (page_size,)
            values += (num_of_element_to_skip,)
            select += "LIMIT ? OFFSET ?"
        print(f"{select} {values}")
        list_of_items = self._cursor.execute(select, values).fetchall()

        cursor_desc_copy = copy.deepcopy(self._cursor.description)

        # Get the total
        if not page_size:
            response.total = len(list_of_items)

        # None or empty
        if not list_of_items:
            return response

        for item in list_of_items:

            obj = {}
            for idx, attribute in enumerate(cursor_desc_copy):
                key_path = attribute[0]
                obj[key_path] = item[idx]

            o = self.load(self._table_name, [], self.model, obj)
            response.items.append(o)

        return response
